version: "3.7"

services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: example-web-server
    volumes:
      - ./src:app/src
      - .app/ts-node-dev.json
    expose:
      - "3333"
    ports:
      - "8080:8080"
      - "9229:9229"
    command: npm start